### ISSUE TITLE
Deep Dark Forrest biome crash

### ISSUE THREAD

**Issue by MysticcX** [finallion/The_Graveyard_Biomes_-FABRIC-#1]
The client will end up randomly crashing and it seems to be because of a conflict with this mod's deep dark forrest biome and Minecraft's meadow. I started playing on a new world the other day and I would play within 300 blocks of spawn and there was no Graveyard biome in any of my generated or surrounding chunks. Could leave the world and join back multiple times with no problem but randomly I got this crash saying it was due to a conflict the deep dark forrest and meadow biomes. Couldn't load back into my world.

I was using version 1.4 of the Graveyard Biomes then tried with with version 1.3. When switching back from 1.4 to 1.3 I was able to load back into my save but later that night I got the same crash.

Crash Report:

---- Minecraft Crash Report -------- Minecraft Crash Report ----// Who set us up the TNT?
Time: 2022-11-08 02:10:27Description: Exception generating new chunk
java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / minecraft:meadow]=net.minecraft.class_1959@68e13261}, Reference{ResourceKey[minecraft:worldgen/biome / graveyard_biomes:deep_dark_forest]=net.minecraft.class_1959@4d04d844}] at net.minecraft.class_7510.method_44210(class_7510.java:100) at net.minecraft.class_2794.mdae8d73$lambda$updateFeaturesPerStep$1$0(class_2794.java:5354) at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) at net.minecraft.class_2794.method_12102(class_2794.java:397) at net.minecraft.class_2806.method_20613(class_2806.java:145) at net.minecraft.class_2806.method_12154(class_2806.java:292) at net.minecraft.class_3898.method_17225(class_3898.java:679) at com.mojang.datafixers.util.Either$Left.map(Either.java:38) at net.minecraft.class_3898.method_17224(class_3898.java:673) at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) at net.minecraft.class_3900.method_17634(class_3900.java:62) at net.minecraft.class_3846.method_16907(class_3846.java:91) at net.minecraft.class_3846.method_16900(class_3846.java:146) at net.minecraft.class_3846.run(class_3846.java:102) at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

- Full Crash Report via Pastebin -
[CrashBin](https://pastebin.com/dfrqGjb3)

**Comment by finallion** [comment]
Fixed in version 1.5.
