### ISSUE TITLE
Water texture issue with physics mod

### ISSUE THREAD

**Issue by SylisMC** [finallion/The_Graveyard_Biomes_-FABRIC-#3]
only happens if ocean physics are enabled
I'm playing 1.19.2 but I double the version makes a difference with this issue
https://minecraftphysicsmod.com/
![2023-12-03_07 07 37](https://github.com/finallion/Nyctophobia-FABRIC/assets/19602662/e1950359-cbb0-48e7-ab49-316266fac745)

**Comment by SylisMC** [comment]
Problem is consistent with all of your biomes that recolor water

**Comment by finallion** [comment]
The recoloring of water is a vanilla feature and a standard addition when creating biomes. I dont see how this is a problem on my side

**Comment by SylisMC** [comment]
Gotcha, i see similar issues with some other mods but not with others. im not sure what the difference is. im not familiar with the water recolor section of resource packs. ill try to see if its something i can remove for compatibility i guess
