### ISSUE TITLE
Please make the biomes rarer

### ISSUE THREAD

**Issue by SalmonSnakeD** [finallion/The_Graveyard_Biomes_-FABRIC-#4]
I just have a quick suggestion for the developer about the biome generation, it's a lot of text because I wanted to be precise.

So I think that the biomes are way too common in the overworld. You can find many custom biomes in a 1000x1000 radius which is too often in my opinion at least. I think that they should be rarer, or at least configurable how rare they are. (It would be handy also if we could configure what biomes can generate at all.)

I think that the ancient dead coral reef biome doesn't fit any of the surrounding biomes at all, the white water is too noticeable and weird, it should be a white shade of blue, not a pure white. But that's just my opinion, don't get offended by this little opinion about the white coloring.
The ancient coral reefs are usually super small and look like they are not supposed to be there, to fix this (and the issue of biomes overall generating too often) you could make every biome rarer, like a few different custom biomes in a 4000x4000 radius, and make the biomes be at least 50x50 large, and add more detail to make them better.

But of course you don't have to do anything, this is a free project, and I am just giving free ideas and some feedback for it 👍

**Comment by finallion** [comment]
I cannot influence the rarity of biomes due to how minecraft handles biome placement since the 1.18 update. The same with "microbiomes" as a direct consequence of those changes - this is a vanilla issue as well. You can try to change the rarity in the config via TerraBlender.

**Comment by Sunconure11** [comment]
@finallion I'm having the opposite. They are too rare.

**Comment by Sunconure11** [comment]
I'm on 1.19.2 though, of note.
